import {
  Devise,
  Role,
  StatutCommande,
  StatutOrdonnance,
  StatutVente,
} from '@prisma/client';

export const SEED_PASSWORD = 'pharma2026';

export const users = [
  {
    key: 'admin',
    nom: 'Kabila',
    prenom: 'Jean-Pierre',
    email: 'admin@pharmacie-centrale.cd',
    role: Role.ADMIN,
  },
  {
    key: 'pharmacien',
    nom: 'Mukeba',
    prenom: 'Marie',
    email: 'marie.mukeba@pharmacie-centrale.cd',
    role: Role.PHARMACIEN,
  },
  {
    key: 'caissier',
    nom: 'Tshilombo',
    prenom: 'Grace',
    email: 'grace.tshilombo@pharmacie-centrale.cd',
    role: Role.CAISSIER,
  },
  {
    key: 'client1',
    nom: 'Lumumba',
    prenom: 'Patrice',
    email: 'p.lumumba@gmail.com',
    role: Role.CLIENT,
  },
  {
    key: 'client2',
    nom: 'Kabongo',
    prenom: 'Amina',
    email: 'a.kabongo@yahoo.fr',
    role: Role.CLIENT,
  },
  {
    key: 'client3',
    nom: 'Mbuyi',
    prenom: 'David',
    email: 'd.mbuyi@outlook.com',
    role: Role.CLIENT,
  },
] as const;

export const patients = [
  {
    key: 'emmanuel',
    nom: 'Kazadi',
    prenom: 'Emmanuel',
    telephone: '+243812345678',
    adresse: 'Av. du Commerce, Gombe, Kinshasa',
  },
  {
    key: 'claudine',
    nom: 'Nsimba',
    prenom: 'Claudine',
    telephone: '+243823456789',
    adresse: 'Quartier Ma Campagne, Kinshasa',
  },
  {
    key: 'joseph',
    nom: 'Mukendi',
    prenom: 'Joseph',
    telephone: '+243834567890',
    adresse: 'Quartier Bandalungwa, Kinshasa',
  },
  {
    key: 'beatrice',
    nom: 'Tshisekedi',
    prenom: 'Béatrice',
    telephone: '+243845678901',
    adresse: 'Quartier Lemba, Kinshasa',
  },
] as const;

export const fournisseurs = [
  {
    nom: 'PharmaDistrib RDC',
    telephone: '+243998001122',
    email: 'contact@pharmadistrib.cd',
    adresse: 'Kinshasa, RDC',
  },
  {
    nom: 'MedSupply Congo',
    telephone: '+243998003344',
    email: 'commandes@medsupply.cd',
    adresse: 'Lubumbashi, RDC',
  },
  {
    nom: 'SantéPlus Import',
    telephone: '+243998005566',
    email: 'achats@santeplus.cd',
    adresse: 'Gombe, Kinshasa',
  },
] as const;

/** Stock final après ventes finalisées (vente EN_COURS non déduite) */
export const medicaments = [
  {
    key: 'paracetamol',
    nom: 'Paracétamol 500mg',
    description: 'Antalgique et antipyrétique — 20 comprimés par boîte',
    prixCDF: '3500',
    prixUSD: '1.25',
    categorie: 'Antalgique',
    unite: 'boîte',
    quantite: 120,
    seuilMinimum: 20,
  },
  {
    key: 'amoxicilline',
    nom: 'Amoxicilline 500mg',
    description: 'Antibiotique à large spectre — 12 gélules par boîte',
    prixCDF: '8000',
    prixUSD: '2.85',
    categorie: 'Antibiotique',
    unite: 'boîte',
    quantite: 45,
    seuilMinimum: 15,
  },
  {
    key: 'ibuprofene',
    nom: 'Ibuprofène 400mg',
    description: 'Anti-inflammatoire non stéroïdien — 30 comprimés',
    prixCDF: '5500',
    prixUSD: '1.95',
    categorie: 'Anti-inflammatoire',
    unite: 'boîte',
    quantite: 8,
    seuilMinimum: 15,
  },
  {
    key: 'artemether',
    nom: 'Artéméther-Luméfantrine',
    description: 'Traitement antipaludéen — 24 comprimés',
    prixCDF: '12000',
    prixUSD: '4.30',
    categorie: 'Antipaludéen',
    unite: 'boîte',
    quantite: 5,
    seuilMinimum: 10,
  },
  {
    key: 'omeprazole',
    nom: 'Oméprazole 20mg',
    description: 'Inhibiteur de la pompe à protons — 14 gélules',
    prixCDF: '7200',
    prixUSD: '2.55',
    categorie: 'Gastro-entérologie',
    unite: 'boîte',
    quantite: 60,
    seuilMinimum: 10,
  },
  {
    key: 'metformine',
    nom: 'Metformine 500mg',
    description: 'Antidiabétique oral — 60 comprimés',
    prixCDF: '6500',
    prixUSD: '2.30',
    categorie: 'Antidiabétique',
    unite: 'boîte',
    quantite: 35,
    seuilMinimum: 10,
  },
  {
    key: 'vitamineC',
    nom: 'Vitamine C 1000mg',
    description: 'Complément vitaminique — 20 comprimés effervescents',
    prixCDF: '4000',
    prixUSD: '1.40',
    categorie: 'Vitamine',
    unite: 'tube',
    quantite: 90,
    seuilMinimum: 15,
  },
  {
    key: 'serum',
    nom: 'Sérum physiologique 500ml',
    description: 'Solution saline isotonique pour lavage et irrigation',
    prixCDF: '2800',
    prixUSD: '1.00',
    categorie: 'Soin',
    unite: 'flacon',
    quantite: 3,
    seuilMinimum: 10,
  },
  {
    key: 'doliprane',
    nom: 'Doliprane 1000mg',
    description: 'Paracétamol à libération prolongée — 8 comprimés',
    prixCDF: '4200',
    prixUSD: '1.50',
    categorie: 'Antalgique',
    unite: 'boîte',
    quantite: 55,
    seuilMinimum: 15,
  },
  {
    key: 'cotrimoxazole',
    nom: 'Cotrimoxazole 480mg',
    description: 'Antibiotique combiné — 20 comprimés',
    prixCDF: '5000',
    prixUSD: '1.80',
    categorie: 'Antibiotique',
    unite: 'boîte',
    quantite: 25,
    seuilMinimum: 10,
  },
] as const;

export const ordonnances = [
  {
    key: 'emmanuel_validee',
    patientKey: 'emmanuel',
    prescripteur: 'Dr. Mukamba — Clinique Gombe',
    statut: StatutOrdonnance.VALIDEE,
    imageUrl: null,
    linkedVenteKey: 'vente1',
  },
  {
    key: 'claudine_attente',
    patientKey: 'claudine',
    prescripteur: 'Dr. Bokamba — Hôpital Général de Kinshasa',
    statut: StatutOrdonnance.EN_ATTENTE,
    imageUrl: null,
    linkedVenteKey: null,
  },
  {
    key: 'joseph_refusee',
    patientKey: 'joseph',
    prescripteur: 'Dr. Kabeya — Cabinet Médical Bandal',
    statut: StatutOrdonnance.REFUSEE,
    imageUrl: null,
    linkedVenteKey: null,
  },
  {
    key: 'beatrice_validee',
    patientKey: 'beatrice',
    prescripteur: 'Dr. Mwamba — Polyclinique Lemba',
    statut: StatutOrdonnance.VALIDEE,
    imageUrl: null,
    linkedVenteKey: null,
  },
] as const;

export const ventes = [
  {
    key: 'vente1',
    caissierKey: 'caissier',
    patientKey: 'emmanuel',
    ordonnanceKey: 'emmanuel_validee',
    montantTotal: '19500',
    devise: Devise.CDF,
    statut: StatutVente.FINALISEE,
    lignes: [
      { medicamentKey: 'amoxicilline', quantite: 2, prixUnitaire: '8000', devise: Devise.CDF },
      { medicamentKey: 'paracetamol', quantite: 1, prixUnitaire: '3500', devise: Devise.CDF },
    ],
  },
  {
    key: 'vente2',
    caissierKey: 'caissier',
    patientKey: null,
    ordonnanceKey: null,
    montantTotal: '4.30',
    devise: Devise.USD,
    statut: StatutVente.FINALISEE,
    lignes: [
      { medicamentKey: 'doliprane', quantite: 1, prixUnitaire: '1.50', devise: Devise.USD },
      { medicamentKey: 'vitamineC', quantite: 2, prixUnitaire: '1.40', devise: Devise.USD },
    ],
  },
  {
    key: 'vente3',
    caissierKey: 'caissier',
    patientKey: 'claudine',
    ordonnanceKey: null,
    montantTotal: '5500',
    devise: Devise.CDF,
    statut: StatutVente.EN_COURS,
    lignes: [
      { medicamentKey: 'ibuprofene', quantite: 1, prixUnitaire: '5500', devise: Devise.CDF },
    ],
  },
] as const;

export const commandes = [
  {
    clientKey: 'client1',
    statut: StatutCommande.EN_ATTENTE,
    note: 'Livraison souhaitée à Gombe, appeler avant.',
    codeRetrait: 'CMD-SEED-0001',
    lignes: [
      { medicamentKey: 'paracetamol', quantite: 3 },
      { medicamentKey: 'omeprazole', quantite: 1 },
    ],
  },
  {
    clientKey: 'client2',
    statut: StatutCommande.PRETE,
    note: 'Commande validée — retrait en pharmacie.',
    codeRetrait: 'CMD-SEED-0002',
    lignes: [{ medicamentKey: 'artemether', quantite: 2 }],
  },
  {
    clientKey: 'client3',
    statut: StatutCommande.REFUSEE,
    note: null,
    motifRefus: 'Stock insuffisant — Ibuprofène 400mg (demandé : 10, disponible : 3)',
    refuseAutomatique: true,
    codeRetrait: 'CMD-SEED-0003',
    lignes: [{ medicamentKey: 'ibuprofene', quantite: 10 }],
  },
] as const;
